Iter9
vzveiteskostrami/go-shortener pull request #7
Opened 2023-07-03 08:34 UTC by vzveiteskostrami

2023-07-03 16:38 UTC, valentinsoe commented on cmd/shortener/Cfg/config.go
> +type FileStorageAttr struct {
А зачем нам эта структура? Почему просто не хранить строку?

2023-07-03 17:06 UTC, valentinsoe requested changes
Спасибо за работу!
Прошлый инкремент принял с условием, что код будет разделен на модули(чего не произошло). Очень сложно читать один очень длинный файл.
Из существенных замечаний требующих исправления:
Разделить код на модули
Убрать перечитывание конфигурации
Добавить проверку на Content-Type ответа при его сжатии

2023-07-03 17:06 UTC, valentinsoe commented on cmd/shortener/main.go
> +		if !strings.Contains(r.Header.Get("Accept-Encoding"), "gzip") {
Нет проверки на Content-Type возвращаемого значения(в задании 8 инкремента указан ограниченный список значений, для которых это надо делать.

2023-07-11 19:53 UTC, valentinsoe requested changes
Спасибо за работу.
Я бы поправил имена пакетов на не настолько сокращенные(но это не критичино).
Сжатие корректно работать не будет так написанное.
https://app.pachca.com/chats/5949547?message=63689392

2023-07-11 19:53 UTC, valentinsoe commented on cmd/shortener/main.go
> +	//r.Handle(`/`, cpress.GZIPHandle(logging.WithLogging(setLink())))
Занудство. Лучше не оставлять комментарии, которые не содержат в себе ценности.

2023-07-11 19:53 UTC, valentinsoe commented on git
Лишний файл?

2023-07-11 19:53 UTC, valentinsoe commented on internal/config/config.go
> +func MakeURL(num int64) string {
Я бы сказал, что создавать эти URL не задача пакета config

2023-07-11 19:53 UTC, valentinsoe commented on internal/cpress/cpress.go
> +package cpress
Занудство. Я бы не стал так сокращать название пакетов. Имя compress не сильно длиннее, но сильно очевиднее

2023-07-11 19:53 UTC, valentinsoe commented on internal/cpress/cpress.go
> +		ct := w.Header().Get("Content-Type")
Здесь еще не отрабоотал внутренний обработчик и не установил значение Content-Type.
Сжатие работать не будет.

2023-07-11 19:53 UTC, valentinsoe commented on internal/cpress/cpress.go
> +			(ct == "application/json" || ct == "text/html")) {
Если gzip не поддерживается, проверять Content-Type нет нужды.

2023-07-11 19:53 UTC, valentinsoe commented on internal/cpress/cpress.go
> +		ct := w.Header().Get("Content-Type")
Когда корректно проверять Content-Type - есть обсуждение в пачке.

2023-07-11 19:53 UTC, valentinsoe commented on internal/dbf/dbf.go
> +	sho := StorageURL{}
Занудство. Название переменной неочевидно что означает.

2023-07-11 19:53 UTC, valentinsoe commented on internal/surl/surl.go
> +	if misc.IsNil(url.URL) || url.URL == "" {
url.URL - строка, а не указатель. Она не может принимать значение nil, поэтому проверять на nil ее не нужно

2023-07-12 06:35 UTC, vzveiteskostrami commented on git
С файлом интересное дело. Я его уже удалял. При каких обстоятельствах он создаётся мне пока неведомо.

2023-07-12 07:06 UTC, vzveiteskostrami commented on internal/config/config.go
> +func MakeURL(num int64) string {
А почему? Все знания о них хранятся внутри пакета config. Я именно из-за этого и перенёс создание url туда. Можно, конечно, и в пакет shorturl, на у этого размещения тоже есть как мысли за, так и против. С моей точки зрения размещать makeurl в любом из этих пакетов примерно равнозначно.

2023-07-12 07:06 UTC, vzveiteskostrami commented on cmd/shortener/main.go
> +	//r.Handle(`/`, cpress.GZIPHandle(logging.WithLogging(setLink())))
Убрал

2023-07-12 07:13 UTC, vzveiteskostrami commented on internal/cpress/cpress.go
> +package cpress
Сделал compressing. Compress мне не очень нравится, так как есть в стандартной библиотеке.

2023-07-12 07:23 UTC, vzveiteskostrami commented on internal/dbf/dbf.go
> +	sho := StorageURL{}
Сделал storageURLItem

2023-07-12 10:49 UTC, valentinsoe commented on internal/config/config.go
> +func MakeURL(num int64) string {
Пакет конфиг ничего знать не хочет ни о каких URL. Это не его задача. Его задача "прочитать" конфигурацию приложения на старте и "раздавать" всем желающим информацию о ней.
Пакет shorturl должен либо уметь читать нужные ему данные из пакета config(а тот в свою очередь гарантировать совместимость публичного интерфейса).
Либо так как ему не нужен весь конфиг, при инициализации получать нужные ему данные и далее ими оперировать. Так на мой взгляд даже лучше - потому что он не зависит от внешнего пакета. Это упрощает тесты и делает код более "атомарным".

2023-07-12 10:54 UTC, valentinsoe commented on internal/cpress/cpress.go
> +			(ct == "application/json" || ct == "text/html")) {
Так пользоваться можно. Проблема такого выражения - его крайне сложно быстро читать. Мне показалось что отрицание относится только к первой его части.

2023-07-12 20:35 UTC, valentinsoe commented on internal/dbf/dbf.go
> +package dbf
Занудство. Не стал комментировать в прошлый раз. Но из названия пакета я не могу понять его назначение.
DB - про базы данных, а f?

2023-07-12 20:37 UTC, valentinsoe commented on git
Его надо удалить локально, закоммитить и запушить эти изменения и более его не создавать:)

2023-07-12 20:38 UTC, valentinsoe approved these changes
Спасибо за исправления!
Работу принимаю

2023-07-13 06:11 UTC, merged